### ISSUE TITLE
Failed to load arena skyblock-warrior

### ISSUE THREAD

**Issue by modsfabio** [SkyWars/SkyWars#198] opened 2016-03-09 00:59 UTC
#### Issue / Bug / Crash: Failed to load arena skyblock-warriors

Server Version: 1.8.9

When did this issue occur?: Startup

**Comment by daboross** [comment] 2016-03-09 07:00
Could you include the startup log from start to finish (including the error)?

**Comment by modsfabio** [comment] 2016-03-09 07:33
http://pastebin.com/QqhQcTcf (http://pastebin.com/QqhQcTcf)
I did not change any files in arena folder..

**Comment by daboross** [comment] 2016-03-09 08:29
Definitely a bug! Let me look into this - I should have a fix soon.

In the meantime, as a temporary fix, it should work to delete the `plugins/SkyWars/arenas` folder. Deleting the `arenas` folder won't lose any data if you haven't created any custom arenas.

**Comment by modsfabio** [comment] 2016-03-09 08:44
Thank you very much.
I thought it was my fault, because I couldn't even start it up once..
Deleting "arenas" didn't work. It's being created again including the 2 configs

**Comment by daboross** [comment] 2016-03-09 08:55
Ok - Yeah, this is definitely a bug on my part, though I'm still trying to find out what exactly is causing it. I *think* `/sw report` should still work after this - could you get a report URL using that command to provide more information?

This bug is almost as if the `.blocks` files were removed from the SkyWars.jar - or they are somehow inaccessible. I'll keep looking into this.

**Comment by daboross** [comment] 2016-03-09 09:26
I can't figure out exactly what's wrong, but I've made a dev build update which should tell us exactly what's happening.

Could you try using this plugin jar and report the error it produces? It should have an error that's at least 2-3 times as long with more information.

[SkyWars-dev-build-for-issue-198.zip](https://github.com/SkyWars/SkyWars/files/164824/SkyWars-dev-build-for-issue-198.zip)

**Comment by modsfabio** [comment] 2016-03-09 09:31
Here the report: http://is.gd/rtPkmg (http://is.gd/rtPkmg)
I will try the DEV-Build, one moment please.

**Comment by modsfabio** [comment] 2016-03-09 09:34
Error Log of DEV-Build: http://pastebin.com/Gknq0at8 (http://pastebin.com/Gknq0at8)

**Comment by modsfabio** [comment] 2016-03-09 09:36
It worked, when I copied the .block files from the .jar to arenas folder..

**Comment by daboross** [comment] 2016-03-09 09:43
Thank you for the error log! I think I know now what I messed up.

There's some new code for loading arenas in 2.1.0, and I hadn't tested it on Windows yet. I'll do that now, and fix it so it will work on Windows as well as linux.

I guess it also makes sense that copying the .blocks files works, I'm glad it does! The issue is with code which loads those files from the jar, so if they already exist it won't run into the problem.

Thank you for your help! There should be a fix for this soon (without requiring copying the .blocks files)!

**Comment by daboross** [comment] 2016-03-10 01:52
Should be fixed as of https://github.com/SkyWars/SkyWars/commit/e1902bd4d9ee53c4bd01f9eaf227642533a370d7 - this will be released in 2.1.1!

Thank you for the report and additional information, it was quite useful!

**Closed by daboross** 2016-03-10 01:52 UTC
Labels: Bug
