### ISSUE TITLE
Points system

### ISSUE THREAD

**Issue by Ssensaxs** [SkyWars/SkyWars#186] opened 2015-02-27 04:36 UTC
Having point system as Skywars-plugin plugin that was abandoned.

http://dev.bukkit.org/bukkit-plugins/skywars-plugin/

**Comment by daboross** [comment] 2016-02-12 03:04
Unfortunately, this project was also abandoned. :(

SkyWars does have a points system, but not a complete one.

**Comment by daboross** [comment] 2016-02-12 03:06
Closing this as a semi-duplicate of https://github.com/SkyWars/SkyWars/issues/69.

**Closed by daboross** 2016-02-12 03:06 UTC
Labels: Question
