### ISSUE TITLE
Random items ins chests based on chance percentage.

### ISSUE THREAD

**Issue by d1One** [SkyWars/SkyWars#161] opened 2014-10-21 22:32 UTC
Feature suggestion:
I noticed all chests in the game are empty, i suppose owners have to manually fill them.
It would be cool to have randomized items spawning in chests with two categories:
- Normal chests for islands: These would have basic items.
- Trapped chests: these would have better items, to be used in the main center island.
The random item lists should be per arena, so we can theme them.

**Comment by daboross** [comment] 2016-02-17 20:10
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work.

I'm going to close this now as a duplicate of https://github.com/SkyWars/SkyWars/issues/117, just in order to have all discussion of this feature in one place. If you still use SkyWars, continue discussion there.

**Closed by daboross** 2016-02-17 20:10 UTC
Labels: Duplicate
