### ISSUE TITLE
Arena world void bug 

### ISSUE THREAD

**Issue by thomasreichmann** [SkyWars/SkyWars#204] opened 2016-03-23 21:35 UTC
#### Issue / Bug / Crash:

Server Version:1.8

When did this issue occur?:On the start of a game

What did you expect to happen?:The arena to start in a void world with the arena

What happened?:When a skywars game starts, the player is teleported to the skywars world and to the arena but, there is no void only grass in the bottom, so players can just get water and go to de bottom of the map and run away

Output url from `/sw report`: http://is.gd/VTyXh4

Any errors in console?: NOP

**Comment by daboross** [comment] 2016-03-23 21:52
Ok, this has happened before but I've been unable to reproduce, hoping I can actually fix it this time.

Are you using any multiple world management plugins?

**Comment by thomasreichmann** [comment] 2016-03-23 21:57
I'm using multiverse

**Comment by thomasreichmann** [comment] 2016-03-24 23:57
Find the solution! Qhen i created the arena, i did the setpos too low on the arena.

**Comment by daboross** [comment] 2016-03-25 02:03
Ahh, that would do it!

I was trying to figure out what caused this but I couldn't really find anything yet, but that would definitely cause this! Thank you for finding that.

SkyWars does copy all blocks from the setpos1 to setpos2 location, so if that includes ground, that will happen.

**Comment by thomasreichmann** [comment] 2016-03-25 02:31
One more thing, Now when a game starts, the players spawn outside the spawnpoint and fall in to the void

**Comment by daboross** [comment] 2016-03-25 03:22
Hmm, now that **is** strange. Could you share the .blocks and .yml files for your arena?

**Comment by thomasreichmann** [comment] 2016-03-25 18:06
Here http://www.mediafire.com/download/isnid9z3833c1n6/arenas.rar

**Comment by daboross** [comment] 2016-03-25 20:19
Thanks! I'll get on testing that now.

**Comment by daboross** [comment] 2016-03-25 20:41
Ok, as far as I can tell with that arena all players do spawn in the right places.

This might be due to players lagging when teleporting to the new arena and falling through before the chunks fully load, but I'm not sure how to test that with just my localhost server, or what could be done to fix it.

When this happens, do all players fall into void, or only some of them each game?

**Comment by thomasreichmann** [comment] 2016-03-25 20:49
Well, my i only tested with 4 players max, but yes everyone spawn in the sky

**Comment by daboross** [comment] 2016-03-25 21:03
Ok, I'm having a bit of trouble reproducing this but I'll try a different server setup.

You are sure that the normal arena is the one which is being chosen? Lowercase like the files you shared.

While falling into the void, do the players at all see the arena, or do they just see void all around? Can they tell or see the place where they should have spawned?

**Comment by thomasreichmann** [comment] 2016-03-25 21:43
Yes, the arena normal is the one that the palyers are teleported to, and the playres can see the arena while they fall

**Comment by thomasreichmann** [comment] 2016-03-25 22:45
well, somehow by just restarting the server 1-4 times the players now spawn on the islands.

**Comment by daboross** [comment] 2016-03-25 23:52
Hmm, strange. I'll keep looking into this but if it happens again will you tell me?

**Comment by thomasreichmann** [comment] 2016-03-26 01:56
yes

**Comment by daboross** [comment] 2016-03-27 06:06
I'm going to be away for a few days, I won't be able to respond until Thursday at least.

I'm going to close this for now as it seems to be resolved. If the issue happens again, comment and I will re-open when I get back!

**Closed by daboross** 2016-03-27 06:06 UTC
Labels: Bug
