### ISSUE TITLE
main-config problem

### ISSUE THREAD

**Issue by rskywolf** [SkyWars/SkyWars#209] opened 2016-04-23 23:04 UTC
#### Issue / Bug / Crash: I changed the main-config file (by adding a new arena) and now it won't work

Server Version:1.8.x

When did this issue occur?:Whenever I open up my server

What did you expect to happen?:It to work normally and a new arena to be added

What happened?:When I opened the server, there was an error for the SkyWars plugin and it would not load

Output url from `/sw report`:
```
[15:54:38 INFO]: [SkyWars] Enabling SkyWars v2.1.3
[15:54:38 ERROR]: [SkyWars] Startup failed
net.daboross.bukkitdev.skywars.StartupFailedException: Failed to load configuration
        at net.daboross.bukkitdev.skywars.SkyWarsPlugin.startPlugin(SkyWarsPlugin.java:135) ~[SkyWars.jar:skywars-2.1.3]
        at net.daboross.bukkitdev.skywars.SkyWarsPlugin.onEnable(SkyWarsPlugin.java:122) [SkyWars.jar:skywars-2.1.3]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [spigot.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [spigot.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [spigot.jar:git-Spigot-550ebac-7019900]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: org.bukkit.configuration.InvalidConfigurationException: Failed to load C:\Users\Sky Wolf\Desktop\Spigot Server\plugins\SkyWars\main-config.yml as a YAML configuration
        at net.daboross.bukkitdev.skywars.config.SkyFileConfig.load(SkyFileConfig.java:66) ~[SkyWars.jar:skywars-2.1.3]
        at net.daboross.bukkitdev.skywars.config.SkyWarsConfiguration.load(SkyWarsConfiguration.java:93) ~[SkyWars.jar:skywars-2.1.3]
        at net.daboross.bukkitdev.skywars.config.SkyWarsConfiguration.<init>(SkyWarsConfiguration.java:86) ~[SkyWars.jar:skywars-2.1.3]
        at net.daboross.bukkitdev.skywars.SkyWarsPlugin.startPlugin(SkyWarsPlugin.java:133) ~[SkyWars.jar:skywars-2.1.3]
        ... 12 more
Caused by: org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
 in 'string', line 9, column 23:
    config-version: 2debug: falseskip-uuid-version-check:  ...
                          ^

        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[spigot.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[spigot.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[spigot.jar:git-Spigot-550ebac-7019900]
        at net.daboross.bukkitdev.skywars.config.SkyFileConfig.load(SkyFileConfig.java:62) ~[SkyWars.jar:skywars-2.1.3]
        at net.daboross.bukkitdev.skywars.config.SkyWarsConfiguration.load(SkyWarsConfiguration.java:93) ~[SkyWars.jar:skywars-2.1.3]
        at net.daboross.bukkitdev.skywars.config.SkyWarsConfiguration.<init>(SkyWarsConfiguration.java:86) ~[SkyWars.jar:skywars-2.1.3]
        at net.daboross.bukkitdev.skywars.SkyWarsPlugin.startPlugin(SkyWarsPlugin.java:133) ~[SkyWars.jar:skywars-2.1.3]
        ... 12 more
Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
 in 'string', line 9, column 23:
    config-version: 2debug: falseskip-uuid-version-check:  ...
                          ^

        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:871) ~[spigot.jar:git-Spigot-550ebac-7019900]
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360) ~[spigot.jar:git-Spigot-550ebac-7019900]
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[spigot.jar:git-Spigot-550ebac-7019900]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558) ~[spigot.jar:git-Spigot-550ebac-7019900]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[spigot.jar:git-Spigot-550ebac-7019900]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[spigot.jar:git-Spigot-550ebac-7019900]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:226) ~[spigot.jar:git-Spigot-550ebac-7019900]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot.jar:git-Spigot-550ebac-7019900]
        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot.jar:git-Spigot-550ebac-7019900]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot.jar:git-Spigot-550ebac-7019900]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[spigot.jar:git-Spigot-550ebac-7019900]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481) ~[spigot.jar:git-Spigot-550ebac-7019900]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:400) ~[spigot.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[spigot.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[spigot.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[spigot.jar:git-Spigot-550ebac-7019900]
        at net.daboross.bukkitdev.skywars.config.SkyFileConfig.load(SkyFileConfig.java:62) ~[SkyWars.jar:skywars-2.1.3]
        at net.daboross.bukkitdev.skywars.config.SkyWarsConfiguration.load(SkyWarsConfiguration.java:93) ~[SkyWars.jar:skywars-2.1.3]
        at net.daboross.bukkitdev.skywars.config.SkyWarsConfiguration.<init>(SkyWarsConfiguration.java:86) ~[SkyWars.jar:skywars-2.1.3]
        at net.daboross.bukkitdev.skywars.SkyWarsPlugin.startPlugin(SkyWarsPlugin.java:133) ~[SkyWars.jar:skywars-2.1.3]
        ... 12 more
[15:54:38 INFO]: [SkyWars] Disabling SkyWars v2.1.3
```

Any errors in console?: don't think so
[main-config.txt](https://github.com/SkyWars/SkyWars/files/233188/main-config.txt)

#### Feature Request:

What would you like to be added?:

**Comment by daboross** [comment] 2016-04-24 16:03
It seems you have a lot of newlines missing from your main-config.yml.

What editor did you use to change the main-config.yml? Whichever one it was has merged many lines in the file together, and that's what is causing the error.

**Comment by daboross** [comment] 2016-05-02 00:10
Since you haven't replied in 7 days, I'm going to assume the issue is either fixed you are no longer using SkyWars.

If you are still experiencing the issue, please reply, and I will help further.

**Closed by daboross** 2016-05-02 00:10 UTC
Labels: Bug, Question, Requires more information

**Comment by rainbowdude6** [comment] 2017-01-05 18:49
i have the same problem her is my config file can u tell me if the is any problem with it


# ####### config.yml #######
# 
# All comment changes will be removed.
# 
# For documentation, please visit 
# https://dabo.guru/projects/skywars/configuring-skywars
# #########
config-version: 2
debug: false
report-statistics: true
arena-order: RANDOM
message-prefix: '&8[&cSkyWars&8]&a '
save-inventory: true
save-experience: true
save-position-gamemode-health: true
enabled-arenas:
- skyblock-warriors
- water-warriors
- Jungle
- Village
locale: en
skywars-arena-gamerules:
  doDaylightCycle: 'false'
skip-respawn-screen: false
points:
  enable-points: true
  win-point-diff: 7
  death-point-diff: -2
  kill-point-diff: 1
  max-save-interval: 300
  use-sql: false
  sql:
    host: 127.0.0.1
    port: 3306
    database: minecraft
    username: root
    password: aComplexPassword
    individual-rank-update-interval: 60
economy:
  enable-economy: false
  kill-reward: 2
  win-reward: 10
  reward-messages: true
arena-distance-apart: 200
arena-copying:
  number-of-blocks-to-copy-at-once: 500
command-whitelist:
  whitelist-enabled: true
  treated-as-blacklist: false
  whitelist:
  - /skywars
  - /sw
  - /me
join-sign-lines:
- '&8[&cSkyWars&8]'
- '&8Next Game: &c{name}'
- '&8Players: &2{count}&3/&2{max}'
- '&cClick to join!'
only-broadcast-to-players-in-arena:
  start: false
  death: true
  end: false
  starting-in-start-timer: false
kit-gui:
  show-unavailable-kits: true
  replace-kit-command: false
  auto-show-on-join: true
game-timer:
  time-till-start-after-max-join: 30
  time-till-start-after-any-join: 200
  time-before-start-to-start-arena-copy-operation: 45
  time-after-start-to-freeze-players: 5
  times-to-message-before-start:
  - 600
  - 300
  - 180
  - 60
  - 45
  - 30
  - 15
  - 5
  - 3
  - 2
  - 1
hooks:
  multiverse-core-hook: true
  worldedit-hook: true

**Comment by rskywolf** [comment] 2017-01-06 14:44
I'm not sure. I would try putting some stuff back to the original format
and see if it works and work from there.
Sorry I couldn't help!


On Jan 5, 2017 10:49 AM, "rainbowdude6" <notifications@github.com> wrote:

i have the same problem her is my config file can u tell me if the is any
problem with it
####### config.yml All comment changes will be removed. For documentation,
please visit https://dabo.guru/projects/skywars/configuring-skywars

config-version: 2
debug: false
report-statistics: true
arena-order: RANDOM
message-prefix: '&8[&cSkyWars&8]&a '
save-inventory: true
save-experience: true
save-position-gamemode-health: true
enabled-arenas:

   - skyblock-warriors
   - water-warriors
   - Jungle
   - Village
   locale: en
   skywars-arena-gamerules:
   doDaylightCycle: 'false'
   skip-respawn-screen: false
   points:
   enable-points: true
   win-point-diff: 7
   death-point-diff: -2
   kill-point-diff: 1
   max-save-interval: 300
   use-sql: false
   sql:
   host: 127.0.0.1
   port: 3306
   database: minecraft
   username: root
   password: aComplexPassword
   individual-rank-update-interval: 60
   economy:
   enable-economy: false
   kill-reward: 2
   win-reward: 10
   reward-messages: true
   arena-distance-apart: 200
   arena-copying:
   number-of-blocks-to-copy-at-once: 500
   command-whitelist:
   whitelist-enabled: true
   treated-as-blacklist: false
   whitelist:
      - /skywars
      - /sw
      - /me
      join-sign-lines:
   - '&8[&cSkyWars&8]'
   - '&8Next Game: &c{name}'
   - '&8Players: &2{count}&3/&2{max}'
   - '&cClick to join!'
   only-broadcast-to-players-in-arena:
   start: false
   death: true
   end: false
   starting-in-start-timer: false
   kit-gui:
   show-unavailable-kits: true
   replace-kit-command: false
   auto-show-on-join: true
   game-timer:
   time-till-start-after-max-join: 30
   time-till-start-after-any-join: 200
   time-before-start-to-start-arena-copy-operation: 45
   time-after-start-to-freeze-players: 5
   times-to-message-before-start:
      - 600
      - 300
      - 180
      - 60
      - 45
      - 30
      - 15
      - 5
      - 3
      - 2
      - 1
      hooks:
      multiverse-core-hook: true
      worldedit-hook: true

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SkyWars/SkyWars/issues/209#issuecomment-270724162>, or mute
the thread
