### ISSUE TITLE
Players falls outside of the spawn points

### ISSUE THREAD

**Issue by oscarib** [SkyWars/SkyWars#203] opened 2016-03-22 14:20 UTC
#### Issue / Bug / Crash:
Added spawns seem to be outside the boundaries of my arena. I set them up, but then players, when connected, appears on different locations, most of the times falling into the dark zone.
I did /sw start an arena, then set both upper and lower positions, and then set spawns... but with the given result.

Server Version: Craftbukkit 1.8.8

When did this issue occur?:
Whenver I set a new arena. Default arenas work properly. But my own arenas always are bad, in terms of players spawning

What did you expect to happen?:
Players sitting on islands, as where I set up my spawn points.

What happened?:
All players falls into the dark zone, outise of the spawn points.

Output url from `/sw report`:
http://is.gd/RwAlna

Any errors in console?:
Only kits not being used warnings.

**Comment by daboross** [comment] 2016-03-23 20:43
Yeah, the spawns in the config file are definitely set to be outside the arena boundaries. I'm really not sure why this would happen, but I can try to replicate and fix it.

Just to confirm: You are between the first and second position in both x, y, and z directions when setting the spawn points?

**Comment by oscarib** [comment] 2016-03-24 07:16
Sure I was!
I set first and second positions far far away and i
​n​
opposite corners o
​n​
the cuboid of the island
​ (with //up 1). And then, inside the cuboid, ​the spawn points.

​I've tried it out several times without sucess.

Do I need to directly look at the blocks where I want to set positions and
spawns? (I did)

​I setup this on a different world, just for skywars, and I "/mv import" it
with multiverse. Then, I "/mv tp" to it, in order to to set the arena. ​

​Regards!​
​
​Óscar​

**Comment by daboross** [comment] 2016-03-24 19:03
OK, that all sounds good. I'll try to reproduce this again.

One thing to mention though: SkyWars doesn't ever take the block you are looking at, all the positions that are set are set to you the block your character's head is in. Might that be causing confusion?

**Comment by oscarib** [comment] 2016-03-24 22:10
It shouldn't, since there was enough margin for not making any error with
this.

Please, consider asking me for any kind of testing if you need it.
I'll be out until next monday,  but feel free to ask me whatever testing
you could need me to.

Thanks a lot for your support, guys.

Regards,
Oscar

**Comment by daboross** [comment] 2016-03-25 00:06
Ok, thank you. If it wasn't the head position being used rather than block looking at, it is definitely a bug of some sort.

I'm going to try to reproduce this, but it probably would be helpful to have a copy of your arena to test with. Could you zip and upload **Arena1.blocks** in the **plugins/SkyWars/arenas/** folder?

It isn't necessary, but it would definitely help figure out what's happening. It should work to select a file for upload in the comment box in the issue ticket.

**Comment by oscarib** [comment] 2016-03-25 06:58
Here you have it:


2016-03-25 1:06 GMT+01:00 Dabo Ross <notifications@github.com>:

> Ok, thank you. If it wasn't the head position being used rather than block
> looking at, it is definitely a bug of some sort.
>
> I'm going to try to reproduce this, but it probably would be helpful to
> have a copy of your arena to test with. Could you zip and upload
> *Arena1.blocks* in the *plugins/SkyWars/arenas/* folder?
>
> It isn't necessary, but it would definitely help figure out what's
> happening. It should work to select a file for upload in the comment box in
> the issue ticket.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/SkyWars/SkyWars/issues/203#issuecomment-201079667>
>



-- 
Saludos,
Óscar+

¿Te apuntas? EspañaDeMaria <http://españademaria.es>

**Comment by daboross** [comment] 2016-03-25 20:18
Thank you!

Ok, so this is what I'm seeing happening with the arena: two of the spawns do work, but two of the spawns happen on islands which weren't copied (player shown on the lower left side): https://i.imgur.com/ScXyy06.png. All the spawns seem to be on islands, but the whole arena hasn't been copied - it's been cut off.

I can't think of anything in SkyWars which would cause a large arena to be cut off, but I'll keep testing to see if there are any bugs which could cause this.

Do you think pos1 and pos2 could possibly have been set too far inwards due to SkyWars setting them to the head position rather than cursor position / looked at block?

**Comment by oscarib** [comment] 2016-03-25 20:33
Humm... If so, I should be downgraded to first degree...
I guess I set the cuboid positions far enough of the islands boundaries,
but this pic you have sent is very strange indeed...
Please, let me check it out before you keep debugging... I will try to
enlarge the cuboid, and see what happens.
Will keep you informed.


2016-03-25 21:18 GMT+01:00 Dabo Ross <notifications@github.com>:

> Thank you!
>
> Ok, so this is what I'm seeing happening with the arena: two of the spawns
> do work, but two of the spawns happen on islands which weren't copied
> (player shown on the lower left side): https://i.imgur.com/ScXyy06.png.
> All the spawns seem to be on islands, but the whole arena hasn't been
> copied - it's been cut off.
>
> I can't think of anything in SkyWars which would cause a large arena to be
> cut off, but I'll keep testing to see if there are any bugs which could
> cause this.
>
> Do you think pos1 and pos2 could possibly have been set too far inwards
> due to SkyWars setting them to the head position rather than cursor
> position / looked at block?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/SkyWars/SkyWars/issues/203#issuecomment-201476164>
>



-- 
Saludos,
Óscar+

¿Te apuntas? EspañaDeMaria <http://españademaria.es>

**Comment by oscarib** [comment] 2016-03-25 20:58
Hi Debo,

Now I have checked it out twice. 

This is where my first position was set:
![screenshot at mar 25 21-38-38](https://cloud.githubusercontent.com/assets/16482402/14053795/341466b6-f2d4-11e5-9a8e-22b18f808f35.png)
![screenshot at mar 25 21-42-30](https://cloud.githubusercontent.com/assets/16482402/14053799/3d2bb20e-f2d4-11e5-82a1-5f5dbe03c9d6.png)


And this is where the second point was set:
![screenshot at mar 25 21-40-35](https://cloud.githubusercontent.com/assets/16482402/14053802/4666f04a-f2d4-11e5-99db-bd5922ea6996.png)
![screenshot at mar 25 21-41-04](https://cloud.githubusercontent.com/assets/16482402/14053806/4c1bec48-f2d4-11e5-896c-143723cd505e.png)

I attach once again the new block file:
[Arena1.blocks.zip](https://github.com/SkyWars/SkyWars/files/190077/Arena1.blocks.zip)

If you still see the island cut off, then it is some kind of problem with the boundaries setting.

This is the new report:
http://is.gd/siXm52

And I have make a new try with two players, both of them falling down into the dark bottom.

**Comment by daboross** [comment] 2016-03-25 21:01
Ok, then it is definitely an issue with the SkyWars arena set up command.

**Comment by oscarib** [comment] 2016-03-25 21:22
It seems so

**Comment by daboross** [comment] 2016-03-27 02:27
Actually, could I ask one more thing? Sorry to bother you if this isn't the case. I'm still trying to find the bug in the command, but one possibility occurred.

I just wanted to make sure that the new blocks and arena file enabled are actually the new ones set with those positions. When a new arena is saved, if the name conflicts with an existing arena, a number is added to the end and incremented until the name doesn't conflict. However, and this is my bad, SkyWars doesn't tell you it did this. Could you confirm that the latest set of files is indeed accurate, and the new arena set up didn't get accidentally saved as `Arena11` or `Arena12`?

**Comment by daboross** [comment] 2016-03-27 06:09
I'm going to be away till Thursday, but if you have any update I'll respond to it then. I've tried to find something but I still can't find the bug in arena creation.

SkyWars silently modifying the arena name when saving has been fixed in the latest update (not released), and I'm hoping that was the cause of this issue. If it wasn't though I will continue debugging this on Thursday. Thank you for your help with this issue!

**Comment by oscarib** [comment] 2016-03-27 09:50
Hi, Debo:

All the testing I have been making always included removing all arenas
before, as an obsession as a Java developer (which I am too).

[image: Imágenes integradas 1]

Don't worry about answering too fast. And feel absolutely free to ask me
whatever you need without any worrying at all.

I'm just wanting to build a "private" server for a few friends, and we are
very looking to being able to play SkyWars, so take your time.

Best Regards,
Óscar

2016-03-27 8:09 GMT+02:00 Dabo Ross <notifications@github.com>:

> I'm going to be away till Thursday, but if you have any update I'll
> respond to it then. I've tried to find something but I still can't find the
> bug in arena creation.
>
> SkyWars silently modifying the arena name when saving has been fixed in
> the latest update (not released), and I'm hoping that was the cause of this
> issue. If it wasn't though I will continue debugging this on Thursday.
> Thank you for your help with this issue!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/SkyWars/SkyWars/issues/203#issuecomment-201999555>
>



-- 
Saludos,
Óscar+

¿Te apuntas? EspañaDeMaria <http://españademaria.es>

**Comment by oscarib** [comment] 2016-03-27 09:50
Sorry... D*a*bo.

2016-03-27 11:49 GMT+02:00 Óscar Ibáñez Fernández <oscar.ibafer@gmail.com>:

> Hi, Debo:
>
> All the testing I have been making always included removing all arenas
> before, as an obsession as a Java developer (which I am too).
>
> [image: Imágenes integradas 1]
>
> Don't worry about answering too fast. And feel absolutely free to ask me
> whatever you need without any worrying at all.
>
> I'm just wanting to build a "private" server for a few friends, and we are
> very looking to being able to play SkyWars, so take your time.
>
> Best Regards,
> Óscar
>
> 2016-03-27 8:09 GMT+02:00 Dabo Ross <notifications@github.com>:
>
>> I'm going to be away till Thursday, but if you have any update I'll
>> respond to it then. I've tried to find something but I still can't find the
>> bug in arena creation.
>>
>> SkyWars silently modifying the arena name when saving has been fixed in
>> the latest update (not released), and I'm hoping that was the cause of this
>> issue. If it wasn't though I will continue debugging this on Thursday.
>> Thank you for your help with this issue!
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/SkyWars/SkyWars/issues/203#issuecomment-201999555>
>>
>
>
>
> --
> Saludos,
> Óscar+
>
> ¿Te apuntas? EspañaDeMaria <http://españademaria.es>
>



-- 
Saludos,
Óscar+

¿Te apuntas? EspañaDeMaria <http://españademaria.es>

**Comment by CrypticCabub** [comment] 2016-03-31 19:45
Hey there! I was having the same issue and I believe I may have found the cause (at least partially)

https://gist.github.com/anonymous/03daaf1e54db282f2a0073152ebeb6e3

so I have 3 custom arenas. This report is when the arena "Crystaline" worked fine but "Tree" and "Biomes" did not work. I'm not sure if SkyWars was generating the islands or not (was not able to find them before my testers fell to their deaths at the very least) but I do know that the spawns were way off base if the islands were indeed spawning.

What I realized though was that Crystaline was setup using version 2.1.1 rather than 2.1.2 and when I looked into it you have a new config version (version 2) for the {arenaName}.yml files. It appears there is an inconsistency issue revolving around the addition of yaw and pitch to the location data. either in the serialization/deserialization or the setting of the data in the first place (float vs double perhaps? total stab in the dark there)

I now believe I have 3 working custom arenas which I achieved by using version 2.1.1 to create the arenas and then switching back to 2.1.2 to play on the arenas. Here's the report file from the now working arenas:
https://gist.github.com/anonymous/5e6e26331dbcbf77db1716d049a24807

I have not looked into your source code personally, but the issue appears to be somewhere in the config-version 2 change. perhaps something to do with yaw and pitch?

Hope that helps!
-CrypticCabub

**Comment by CrypticCabub** [comment] 2016-03-31 19:51
also do you think you could add some kind of countdown or other user-friendly auto-start to the lobby queue? something configurable that would allow me to have say 10 people in the queue autostart after 60-90 seconds even though the arenas are for 16 players (rather than giving the forcestart command to the players)

-a feature I would like to see, but only after the spawn bug is cleared up :D 

thanks again!
-Cryptic

**Comment by daboross** [comment] 2016-03-31 20:52
@CrypticCabub Yeah, there's definitely an issue with 2.1.2 with setting up arenas - this particular issue pre-dates that bug though. I'm releasing a 2.1.3 bugfix release now to fix the position bug in v2.1.2, but I think there's still another one I haven't found yet.

With the timer, that is one of the planned features but I haven't had that much time to work on things, so it hasn't been added yet. It will be implemented after a Kit GUI and join signs (according to the poll in the plugin description)!

**Comment by daboross** [comment] 2016-03-31 20:54
@oscarib Ok - that makes sense.

I found one bug in v2.1.2 which could have caused something similar to this, but it hadn't been introduced in v2.1.1 and it isn't the exact same issue. Still trying to figure out what's causing this.

**Comment by oscarib** [comment] 2016-04-01 05:37
WoW! Cool job, that Cryptic's, and many thanks to both!
I will try to figure out if that could help for me as well.
And looking forward to seeing that new features too.
Best Regards, friends.

2016-03-31 22:54 GMT+02:00 Dabo Ross <notifications@github.com>:

> @oscarib <https://github.com/oscarib> Ok - that makes sense.
>
> I found one bug in v2.1.2 which could have caused something similar to
> this, but it hadn't been introduced in v2.1.1 and it isn't the exact same
> issue. Still trying to figure out what's causing this.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/SkyWars/SkyWars/issues/203#issuecomment-204125154>
>



-- 
Saludos,
Óscar+

¿Te apuntas? EspañaDeMaria <http://españademaria.es>

**Comment by oscarib** [comment] 2016-04-05 20:11
Hi, guys,

I have made a fresh start with a bukkit 1.8.8 and SkyWars v2.1.3, and I haven't found any problems with a new arena configuration... So it seems to be working very good. However, I will keep testing, and let you know.

Keep the good work, Dabo!

**Comment by oscarib** [comment] 2016-04-06 20:08
Hi, Dabo,

I have what the bug is all about, 'cause I have had more errors regarding islands boundaries.
The problem is that the position setting and the cuboid structure is being constructed following "natural axis", and if you set the positions where natural axis are gonna cut the islands structure, then the problem arises. 
I don't know how to explain better, but... do you understand?
Because now I can set the boundaries without having any issues: I just need to be sure at the south of the island, to look straight to east (90º) in order to see if my island boundaries are going to be cut or not (adjunsting my position acordingly), and then look at west (270º) to see if the other side of the cuboid is going to cut some part of the island. Then, I "sw setpos1". After that, I just run to the other side of the island (north position), but keeping in mind that I have to position myself in a way that if a look to east and west once again, the island boundaries should get into that line of looking.
Do I explain myself?
This way, everything works properly.

**Comment by daboross** [comment] 2016-05-02 00:00
Sorry for being away from this for a while, but thank you for continuing to figure this out! I wasn't able to figure it out at all.

That makes sense now though, and I'm glad it's working now! I'll add this to the FAQ.

**Comment by daboross** [comment] 2016-06-08 06:30
I guess I'll close this now that it's been added to the wiki. I'm not sure it'd be possible to prevent this from happening without breaking arenas which are placed close to the ground - I guess the best that can be done is inform people in the future! Thank you for reporting this, and spending the time to debug it and write detailed documentation on how to avoid it.

**Closed by daboross** 2016-06-08 06:30 UTC
Labels: Bug

**Comment by oscarib** [comment] 2016-06-08 18:10
Thx 2 u, mate!

2016-06-08 8:30 GMT+02:00 Dabo Ross <notifications@github.com>:
