### ISSUE TITLE
Randomize Chests

### ISSUE THREAD

**Issue by quack123456** [SkyWars/SkyWars#180] opened 2015-01-27 23:34 UTC
How do i make it so i can have chests randomize different materials or do i have to put them in after every match?

**Comment by quack123456** [comment] 2015-01-28 22:33
Bump

**Comment by quack123456** [comment] 2015-01-29 22:07
bump

**Comment by daboross** [comment] 2015-01-30 02:08
no way currently

**Comment by quack123456** [comment] 2015-01-30 02:21
ah so i have to put them in after every match

**Comment by daboross** [comment] 2016-02-17 20:08
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work.

I'm going to close this now as a duplicate of https://github.com/SkyWars/SkyWars/issues/117. If you still use SkyWars, continue discussion there.

**Closed by daboross** 2016-02-17 20:08 UTC
Labels: New feature
